version: "3.10"
services:
  backend:
    build: .
    volumes:
      - .:/scrapperAPI
    ports:
      - "8000:8000"
    container_name: scrapperAPI
    command: python manage.py runserver 0.0.0.0:9000
