# Generated by Django 4.0.5 on 2022-07-02 14:12

import django.db.models.deletion
from django.db import migrations, models

import scrapper.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("original_url", models.URLField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=scrapper.core.models.image_directory,
                    ),
                ),
                ("image_name", models.CharField(max_length=500)),
                ("height", models.FloatField()),
                ("width", models.FloatField()),
                ("mode", models.CharField(max_length=100)),
                ("format", models.CharField(max_length=100)),
                (
                    "parent_url",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.address",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
