name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:10.8
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: scrapper
          POSTGRES_PORT: 5432
        # Set health checks to wait until postgres has started
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with Django test
      env:
        TEST: 1
        DATABASE_NAME: scrapper
        DATABASE_HOST: postgres
        DATABASE_PASSWORD: postgres
        DATABASE_PORT: 5432
        DATABASE_USER: postgres
      run: python manage.py test